# Generated by Django 4.2.4 on 2023-11-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tudolist',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
