# Generated by Django 4.2.4 on 2023-09-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tudolist',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tudolist',
            name='description',
        ),
        migrations.AddField(
            model_name='tudolist',
            name='content',
            field=models.TextField(default=1, max_length=255, verbose_name='Conteudo'),
            preserve_default=False,
        ),
    ]
