# Generated by Django 4.2.4 on 2023-11-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tudolist_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tudolist',
            old_name='created_at',
            new_name='last_modification',
        ),
    ]
